test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ERROR
test_summation (__main__.TestExercice) ... ok

======================================================================
ERROR: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 14, in test_prefixes
    output = exercice.use_prefixes()
  File "/home/runner/work/c03_ch5_exercices-SamyLabassi/c03_ch5_exercices-SamyLabassi/exercice.py", line 21, in use_prefixes
    resultat = resultat.append(nom)
AttributeError: 'NoneType' object has no attribute 'append'

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (errors=1)
